apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pythonapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: my-python-apps
        image: wzacr01/mypython-app01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: sampleacrsecret
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
